### ISSUE TITLE
build errors

### ISSUE THREAD

**Issue by yuriv** [serenadeai/java-tree-sitter#14]
I have run build `./build.py libjava-tree-sitter tree-sitter-c` on the fresh installation and got following feedback:

> Traceback (most recent call last):
  File "./build.py", line 137, in <module>
    build(args.repositories, args.output, args.arch, args.verbose)
  File "./build.py", line 57, in build
    source_mtimes = [os.path.getmtime(__file__)] + [os.path.getmtime(path) for path in source_paths]
  File "./build.py", line 57, in <listcomp>
    source_mtimes = [os.path.getmtime(__file__)] + [os.path.getmtime(path) for path in source_paths]
  File "/usr/lib64/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'libjava-tree-sitter/src/parser.c'

I have install `java-tree-sitter` with modules. Where I am wrong?

**Comment by WhileBug** [comment]
I have the same problem. Have you fixed it?

**Comment by dabico** [comment]
I think the documentation on how to set up the project is not very clear. First of all, the above command is not correct as the help points out:

```bash
$ ./build.py
usage: build.py [-h] [-a ARCH] [-o OUTPUT] [-v] repositories [repositories ...]
build.py: error: the following arguments are required: repositories
```

Fair enough, I try not to specify the output file and let it default to whatever, only to be met with the same flavor of error:

```bash
$ ./build.py tree-sitter-python
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Traceback (most recent call last):
  File "/Users/ozrendabic/Desktop/java-tree-sitter/build.py", line 137, in <module>
    build(args.repositories, args.output, args.arch, args.verbose)
  File "/Users/ozrendabic/Desktop/java-tree-sitter/build.py", line 57, in build
    source_mtimes = [os.path.getmtime(__file__)] + [os.path.getmtime(path) for path in source_paths]
  File "/Users/ozrendabic/Desktop/java-tree-sitter/build.py", line 57, in <listcomp>
    source_mtimes = [os.path.getmtime(__file__)] + [os.path.getmtime(path) for path in source_paths]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'tree-sitter-python/src/parser.c'
```

Upon more investigation, I deduced that you need to clone the official tree-sitter grammar modules (i.e. [tree-sitter-python](https://github.com/tree-sitter/tree-sitter-python)) and include them in the root. I did so, but now receive a completely different error:

```bash
$ ./build.py tree-sitter-python
make: *** No rule to make target `clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
clang: error: no such file or directory: '/Users/ozrendabic/Desktop/java-tree-sitter/tree-sitter/libtree-sitter.a'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 204, in link
    self.spawn(linker + ld_args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/bin/cc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ozrendabic/Desktop/java-tree-sitter/build.py", line 137, in <module>
    build(args.repositories, args.output, args.arch, args.verbose)
  File "/Users/ozrendabic/Desktop/java-tree-sitter/build.py", line 109, in build
    compiler.link_shared_object(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 206, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/usr/bin/cc' failed with exit code 1
```
